import { useState, useEffect } from 'react';
import Head from 'next/head';
import Link from 'next/link';
//import cookie from 'js-cookie';


export default function Home() {
  const [postData,setPostData] = useState(null);
  async function getPosts() {
    const response = await fetch("api/getAllPosts");
    const jsonData = await response.json();
    setPostData(jsonData);
  }
  useEffect(() => {
    getPosts();
  },[]);
  
  //console.log(cookie.get('isAdmin'));
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
  
    {!postData ? (<div>Loading...</div>):(
      <section className='
      h-100  
      d-flex
      flex-column
      justify-content-between
      align-items-center
      pb-5
      '>

        <h1 className='
        display-4 
        text-center
        my-3
        '
        >
          Curious About Websites? 
          &nbsp;
           <small className='
           text-muted
           '>
            TopDev Can help...
            </small>
          </h1>
        
            <div className='container-fluid'>
            <div className='row p-2'>

        {
          
      postData.map((post) => (
        <div className='
        col-12
         col-sm-6
         col-md-4
         col-lg-3
         card
         p-2
         mb-2
         d-flex
         flex-column
         justify-content-between
         justify-content-stretch
         align-items-center
         '
         key={post._id}
         >
          <h2 className='text-center h4'>{post.title}</h2>
          <span>{post.postDate}</span>
          <Link href={`/blogpost/${post.title}`}>Enjoy Post</Link>
        </div>
      ))
      }
        </div>
       </div>
     
      </section>
    ) }
    </>
  )
}
