import { useState, useEffect } from 'react';
import Head from 'next/head';
import Link from 'next/link';



export default function Home() {
  const [postData,setPostData] = useState(null);
  async function getPosts() {
    const response = await fetch("api/getAllPosts");
    const jsonData = await response.json();
    setPostData(jsonData);
  }
  useEffect(() => {
    getPosts();
  },[]);
  
  console.log(postData);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
  
    {!postData ? (<div>Loading...</div>):(
      <section className='
      h-100  
      d-flex
      flex-column
      justify-content-between
      '>
        {
      postData.map((post) => (
        <div className='
         d-flex
         flex-column
         justify-content-between
         align-items-center
         '
         key={post._id}
         >
          <h2>{post.title}</h2>
          <span>{post.postDate}</span>
          <Link href={`/blogpost/${post.title}`}>Enjoy Post</Link>
        </div>
      ))
      }
      </section>
    ) }
    </>
  )
}
