import { useState, useEffect } from 'react';
import Head from 'next/head';
import Link from 'next/link';



export default function Home() {
  const [postData,setPostData] = useState(null);
  async function getPosts() {
    const response = await fetch("api/getAllPosts");
    const jsonData = await response.json();
    setPostData(jsonData);
  }
  useEffect(() => {
    getPosts();
  },[]);
  
  console.log(postData);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
  
    {!postData ? (<div>Loading...</div>):(
      <section className='
      h-100  
      d-flex
      flex-column
      justify-content-between
      align-items-center
      pb-5
      '>

        <h1 className='
        display-4 
        text-center
        my-3
        '
        >
          Curious About Websites? 
          &nbsp;
           <small className='
           text-muted
           '>
            TopDev Can help...
            </small>
          </h1>
          <div className='
             d-flex
             justify-content-between
             align-items-center
             align-items-md-start
             flex-column
             flex-md-row
          '>

        {
      postData.map((post) => (
        <div className='
         card
         w-75
         p-2
         mb-2
         d-flex
         flex-column
         h-100
         justify-content-between
         align-items-center
         '
         key={post._id}
         >
          <h2 className='text-center h4'>{post.title}</h2>
          <span>{post.postDate}</span>
          <Link href={`/blogpost/${post.title}`}>Enjoy Post</Link>
        </div>
      ))
      }
      </div>
      </section>
    ) }
    </>
  )
}
